import { motion } from "framer-motion";
import { Info } from "lucide-react";

const TrustSection = () => {
  return (
    <section className="py-20 bg-card/30">
      <div className="container mx-auto px-4">
        <motion.div
          className="mx-auto max-w-2xl rounded-xl border border-border bg-card p-8 text-center shadow-card"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <div className="mx-auto mb-4 flex h-10 w-10 items-center justify-center rounded-full bg-warning/10">
            <Info className="h-5 w-5 text-warning" />
          </div>
          <p className="text-sm leading-relaxed text-muted-foreground">
            ImageTruth AI provides automated software-based analysis of digital images.
            Results are generated by artificial intelligence and should be independently verified.
          </p>
        </motion.div>
      </div>
    </section>
  );
};

export default TrustSection;
